apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: dev
data:
  DB_HOST: "mysql.dev.svc.cluster.local"
  DB_USER: "root"
  DB_NAME: "saista_bakers"
  DB_PORT: "3306"
  ORDER_SERVICE_URL: "http://order-service.dev.svc.cluster.local:5002"
  USER_SERVICE_URL: "http://user-service.dev.svc.cluster.local:5001"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SENDER_EMAIL: "asadchamp109@gmail.com"
  SMTP_USER: "asadchamp109@gmail.com"
